package koordinator;


/**
* koordinator/StarterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Koordinator.idl
* Dienstag, 6. Mai 2014 11:00 Uhr MESZ
*/

public interface StarterOperations 
{
  void start_ggT_Prozess (int min_delay, int max_delay, int anz);
  void destroy (int id);
  void destroyAll ();
  void exit ();
} // interface StarterOperations
