package koordinator;


/**
* koordinator/ggT_ProzessOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Koordinator.idl
* Dienstag, 6. Mai 2014 11:00 Uhr MESZ
*/

public interface ggT_ProzessOperations 
{
  void setLinkerNachbar (koordinator.ggT_Prozess linker_nachbar);
  void setRechterNachbar (koordinator.ggT_Prozess rechter_nachbar);
  koordinator.ggT_Prozess getLinkerNachbar ();
  koordinator.ggT_Prozess getRechterNachbar ();
  void addRechterChannel (koordinator.Nachricht msg);
  void addLinkerChannel (koordinator.Nachricht msg);
  void set_ggT (int ggt);
  void setMonitor (koordinator.monitor.Monitor m);
  void printErgebnis ();
  String getId ();
  void exit ();
} // interface ggT_ProzessOperations
