package koordinator;


/**
* koordinator/Nachricht.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Koordinator.idl
* Dienstag, 6. Mai 2014 11:00 Uhr MESZ
*/

public final class Nachricht implements org.omg.CORBA.portable.IDLEntity
{
  public koordinator.NachrichtenTyp typ = null;
  public int ggt = (int)0;
  public int sequenz = (int)0;
  public String name_id = null;
  public boolean terminierung = false;

  public Nachricht ()
  {
  } // ctor

  public Nachricht (koordinator.NachrichtenTyp _typ, int _ggt, int _sequenz, String _name_id, boolean _terminierung)
  {
    typ = _typ;
    ggt = _ggt;
    sequenz = _sequenz;
    name_id = _name_id;
    terminierung = _terminierung;
  } // ctor

} // class Nachricht
