package bank;


/**
* bank/MonitorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* Donnerstag, 27. März 2014 08:03 Uhr MEZ
*/

public interface MonitorOperations 
{
  void meldung (String msg);

  //Damit kann die Bank den Monitor beenden.
  void exit ();
} // interface MonitorOperations
