package bank;


/**
* bank/Monitor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* Donnerstag, 27. März 2014 08:03 Uhr MEZ
*/

public interface Monitor extends MonitorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Monitor
