package HelloWorld;


/**
* HelloWorld/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hello.idl
* Mittwoch, 26. März 2014 10:32 Uhr MEZ
*/

public interface HelloOperations 
{
  String sayHello (String Name);
} // interface HelloOperations
