
package web_sensor;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "DisplayNichtBekanntException", targetNamespace = "web_sensor")
public class DisplayNichtBekanntExceptionException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private DisplayNichtBekanntException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public DisplayNichtBekanntExceptionException(String message, DisplayNichtBekanntException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public DisplayNichtBekanntExceptionException(String message, DisplayNichtBekanntException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: web_sensor.DisplayNichtBekanntException
     */
    public DisplayNichtBekanntException getFaultInfo() {
        return faultInfo;
    }

}
