
package web_sensor;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "KoordinatorWahlException", targetNamespace = "web_sensor")
public class KoordinatorWahlException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private KoordinatorWahlException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public KoordinatorWahlException_Exception(String message, KoordinatorWahlException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public KoordinatorWahlException_Exception(String message, KoordinatorWahlException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: web_sensor.KoordinatorWahlException
     */
    public KoordinatorWahlException getFaultInfo() {
        return faultInfo;
    }

}
